### ISSUE TITLE
Create design diagrams

### ISSUE THREAD

**Issue by adilnumancelik** [adilnumancelik/sonar#9]
We need to create class diagrams and sequence diagrams before the midterm report.

**Comment by adilnumancelik** [comment]
We started the discussions and created a high level draft for classes here:

https://docs.google.com/document/d/1X-ypOqgdNv3N313TO3oaXFcPYKNbD8PfMGUq9yvDcjs/edit

**Comment by MehdiSaffar** [comment]
I recommend using https://mermaid-js.github.io/mermaid/#/ to easily generate class and sequence diagrams from code
